name: Run Link Check
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
     steps:
      - name: Use Node.js 
      - uses: actions/setup-node@v4
    with:
      node-version: 20

  link-check:
    runs-on: ubuntu-latest
    steps:
      - run: npx broken-link-checker https://learn.madetech.com --exclude microsoft --exclude linkedin --exclude twitter --exclude codewars.com -ro

    