name: Run Link Check Cron
on: 
  schedule:
    - cron: '50 11 * * *'
jobs:
  link-check:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 
        uses: actions/setup-node@v4
        with:
         node-version: 20
  
      - run: npx broken-link-checker https://learn.madetech.com --exclude microsoft --exclude linkedin --exclude twitter --exclude codewars.com -ro

    