name: Run App build
on:
  push:
    branches:
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm install npm@5
    - run: npm ci
    # - run: npm prettify
    - run: npm test