name: Run Internal App build
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

env:
  TOKEN: ${{secrets.TOKEN}}

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: internal-app

    steps:
    - name: Copy files
      uses: actions/checkout@v4
      
    - name: Use Node.js 
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    # - run: npm install npm@latest
    
    - run: npm install
      
    - run: npm test